### ISSUE TITLE
Error starting docker image

### ISSUE THREAD

**Issue by Davis2019** [oracle/oci-designer-toolkit#16]
Hello
I´m getting this error when starting docker image and running with -it option, do you know what could be the cause ?
[2020-05-19 01:28:47 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-05-19 01:28:47 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2020-05-19 01:28:47 +0000] [1] [INFO] Using worker: sync
[2020-05-19 01:28:47 +0000] [8] [INFO] Booting worker with pid: 8
[2020-05-19 01:28:47 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'okitweb.wsgi'
[2020-05-19 01:28:47 +0000] [8] [INFO] Worker exiting (pid: 8)
[2020-05-19 01:28:47 +0000] [1] [INFO] Shutting down: Master
[2020-05-19 01:28:47 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by toxophilist** [comment]
@Davis2019 this is likely to be because of an error on the -v part of the command and the volume mount failed. If you execute:
```bash
docker inspect -f "{{ .Mounts }}" okit
```
It will show the volumes mounted on the container and there needs to be volumes for okitweb & visualiser mounted with the full path of the extracted directory.

**Comment by andjaram** [comment]
Hi, same issue here. 

C:\Users\andjaram\containers\oci-designer-toolkit> docker run -it --rm -p 80:80 --name okit --hostname okit -v ~/.oci:/root/.oci:Z -v ./okitweb:/okit/okitweb:Z -v ./visualiser:/okit/visualiser:Z -v ./log:/okit/log:Z okit
[2020-05-19 19:25:07 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-05-19 19:25:07 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2020-05-19 19:25:07 +0000] [1] [INFO] Using worker: sync
[2020-05-19 19:25:07 +0000] [8] [INFO] Booting worker with pid: 8
[2020-05-19 19:25:07 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'okitweb.wsgi'
[2020-05-19 19:25:07 +0000] [8] [INFO] Worker exiting (pid: 8)
[2020-05-19 19:25:07 +0000] [1] [INFO] Shutting down: Master

I think is necessary to have oci cli installed in the host ? I'm not very experienced in docker and conatiners , but the part of `-v ~/.oci:/root/.oci:Z`  is searching for a path where normally the oci cli is installed ?

**Comment by toxophilist** [comment]
@andjaram The issue will be the relative reference to the directories if you replace the 
```bash
./okitweb:/okit/okitweb:Z
./visualiser:/okit/visualiser:Z
./log:/okit/log:Z
```
with
```bash
<Absolute Path>/okitweb:/okit/okitweb
<Absolute Path>/visualiser:/okit/visualiser
<Absolute Path>/log:/okit/log
```

This should resolve your issue.

The oci cli does not need to be installed on the host all you need is to create a config in ~/.oci that matches that defined in https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm
