### ISSUE TITLE
'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401

### ISSUE THREAD

**Issue by mantechexperts** [oracle/oci-designer-toolkit#203]
I tried to build as per the instructions and everytime when i go for query i am getting the error 

========
oci.exceptions.ServiceError: {'opc-request-id': 'C81E4F83E7C74A74BED9B09D0160769E/984643E7E585D68F934783B3D2996B50/B6F90E9CB91F1F86CE3766875B6C55D1', 'code': 'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401}
INFO: Using Profile : DEFAULT
INFO: {'opc-request-id': '38755B011605417E82CD898E5E8341ED/1798A6426B668F4DC67ACA486FB784A5/9177618CC40FB813D3664DE5CD70F064', 'code': 'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401}
INFO: The required information to complete authentication was not provided or was incorrect.
ERROR: {'opc-request-id': '38755B011605417E82CD898E5E8341ED/1798A6426B668F4DC67ACA486FB784A5/9177618CC40FB813D3664DE5CD70F064', 'code': 'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/okit/okitweb/okitOci.py", line 191, in ociCompartment
    tenancy = oci_tenancies.listCompartments()
  File "/okit/visualiser/facades/ociTenancy.py", line 39, in listCompartments
    tenancy_json = self.get(self.getTenancy())
  File "/okit/visualiser/facades/ociTenancy.py", line 30, in get
    tenancy = self.client.get_tenancy(tenancy_id=tenancy_id).data
  File "/usr/local/lib/python3.6/site-packages/oci/identity/identity_client.py", line 4861, in get_tenancy
    response_type="Tenancy")
  File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 272, in call_api
    response = self.request(request)
  File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 384, in request
    self.raise_service_error(request, response)
  File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 554, in raise_service_error
    original_request=request)
oci.exceptions.ServiceError: {'opc-request-id': '38755B011605417E82CD898E5E8341ED/1798A6426B668F4DC67ACA486FB784A5/9177618CC40FB813D3664DE5CD70F064', 'code': 'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401}
INFO: Artifact : Compartment
INFO: Using Profile : DEFAULT
INFO: ---- Processing Compartment
INFO: {'opc-request-id': '174916CA8F5644409FCF37721A612AED/883EB74BCD4BEE16D4F05E7718582D21/B97F73ECBDCDCF4C2A70D4CF531707AA', 'code': 'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401}
INFO: The required information to complete authentication was not provided or was incorrect.
ERROR: {'opc-request-id': '174916CA8F5644409FCF37721A612AED/883EB74BCD4BEE16D4F05E7718582D21/B97F73ECBDCDCF4C2A70D4CF531707AA', 'code': 'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/okit/okitweb/okitOci.py", line 246, in ociArtifacts
    response_json = oci_compartments.get(compartment_id=query_json['compartment_id'])
  File "/okit/visualiser/facades/ociCompartment.py", line 40, in get
    compartment = self.client.get_compartment(compartment_id=compartment_id).data
  File "/usr/local/lib/python3.6/site-packages/oci/identity/identity_client.py", line 4088, in get_compartment
    response_type="Compartment")
  File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 272, in call_api
    response = self.request(request)
  File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 384, in request
    self.raise_service_error(request, response)
  File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 554, in raise_service_error
    original_request=request)
oci.exceptions.ServiceError: {'opc-request-id': '174916CA8F5644409FCF37721A612AED/883EB74BCD4BEE16D4F05E7718582D21/B97F73ECBDCDCF4C2A70D4CF531707AA', 'code': 'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401}
==============

**Comment by mantechexperts** [comment]
=======
It was my mistake, i thought that my key was updated in OCI console. but somehow got deleted
i can able to login now
==============

**Comment by mantechexperts** [comment]
selft troubleshooting
