### ISSUE TITLE
Cost Estimator Issue

### ISSUE THREAD

**Issue by sgmphil** [oracle/oci-designer-toolkit#311]
I have noticed that the cost estimator always estimates the prices for PAYG and Annual Flex to be the same. These prices should differ. Thank you for looking into this.

-Phil

**Comment by sgmphil** [comment]
I just updated to 0.21.0 - good job on some of the fixes. The cost estimator is still having problems, it now hangs on some containers. Here is the what I found in the log:

INFO: Generate Pricing Estimate for OKIT Json
[2021-05-05 14:01:42 +0000] [46] [ERROR] Error handling request /okit/pricing/estimate
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/github/oci-designer-toolkit/okitweb/okitPricing.py", line 37, in pricingEstimate
    return json.dumps(estimator.estimate(), sort_keys=False, indent=2, separators=(',', ': '))
  File "/okit/visualiser/model/okitCostEstimator.py", line 29, in estimate
    self.cost_estimate = okit_price_v2.load_json(self.okit_json)
  File "/okit/visualiser/model/okit_price_v2.py", line 62, in load_json
    OKIT_RESULTS = price_calculator(filename, all_resources)
  File "/okit/visualiser/model/okit_price_v2.py", line 330, in price_calculator
    ocpu_price = calculator.get_oci_price_ords(Compute_SKU)
  File "/okit/visualiser/model/calculator.py", line 23, in get_oci_price_ords
    return pay_as_you_go, monthly_commit, sku
UnboundLocalError: local variable 'pay_as_you_go' referenced before assignment

**Comment by toxophilist** [comment]
Should be resolved in 0.34.0
