### ISSUE TITLE
Cannot generate terraform when NSG have Rules

### ISSUE THREAD

**Issue by LotToLearn** [oracle/oci-designer-toolkit#440]
Hi,

I have 3 NSG.. Validation was FINE on okit console, had to look in LOGS to find the issue -- strange because validation succeeded when I hit the option.

I had to end up removing all the security rules for my NSG. I tried one at a time, keeping rules and then deleting. Eventually all 3 had everything deleted, and it worked.

First one failed, deleted all rules eventually, then it passed, repeat for 2 and 3.

This is the log
INFO: Processing Network Security Group Information Dbnsg
ERROR: 'description'
Traceback (most recent call last):
  File "/github/oci-designer-toolkit/okitweb/okitWebDesigner.py", line 504, in generate
    generator.generate()
  File "/okit/visualiser/generators/okitGenerator.py", line 171, in generate
    self.renderNetworkSecurityGroup(network_security_group)
  File "/okit/visualiser/generators/okitGenerator.py", line 1402, in renderNetworkSecurityGroup
    jinja2_security_rule["description"] = self.generateJinja2Variable('security_rule_{0:02d}_description'.format(rule_number), rule["description"], standardisedName)

**Comment by toxophilist** [comment]
@LotToLearn I can not reproduce this but it looks like your json is missing the description element for the rules which is rather odd. Can you check the original json in the json view to see if description is there.
