### ISSUE TITLE
ERROR: 'key_file'

### ISSUE THREAD

**Issue by davidkhala** [oracle/oci-designer-toolkit#458]
We found a weird bug that even the config file is properly loaded as volume, OKIT cannot read the 'key_file' property

```
INFO: Reading Json File : /github/oci-designer-toolkit/okitweb/static/okit/palette/palette.json
INFO: Config Sections ['DEFAULT']
INFO: Config Sections ['DEFAULT']
INFO: Config Sections {'sections': ['DEFAULT']}
ERROR: 'key_file'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/github/oci-designer-toolkit/okitweb/okitWebDesigner.py", line 586, in configValidate
    response = {"results": validateConfigFile()}
  File "/github/oci-designer-toolkit/okitweb/okitWebDesigner.py", line 116, in validateConfigFile
    key_file = config[section]['key_file']
  File "/usr/lib64/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'key_file'
INFO: []
INFO: Config Settings {'gitsections': []}
INFO: []
INFO: Reading Json File : /okit/instance/templates/reference_architecture/database/sql_server.json
INFO: Reading Json File : /okit/instance/templates/reference_architecture/database/cockroachdb_cluster.json
INFO: Reading Json File : /okit/instance/templates/reference_architecture/database/mysql_ha_cluster.json
[2021-09-10 07:51:38 +0000] [41] [ERROR] Error handling request /okit/oci/regions/DEFAULT
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/github/oci-designer-toolkit/okitweb/okitOci.py", line 227, in ociRegions
    oci_region_query = OCIRegionQuery(profile=profile)
  File "/okit/visualiser/query/ociRegionQuery.py", line 33, in __init__
    super(OCIRegionQuery, self).__init__(config=config, configfile=configfile, profile=profile)
  File "/okit/visualiser/facades/ociConnection.py", line 41, in __init__
    self.signerFromConfig()
  File "/okit/visualiser/facades/ociConnection.py", line 64, in signerFromConfig
    self.loadConfig()
  File "/okit/visualiser/facades/ociConnection.py", line 87, in loadConfig
    self.config = oci.config.from_file(profile_name=self.profile)
  File "/usr/local/lib/python3.6/site-packages/oci/config.py", line 106, in from_file
    raise ConfigFileNotFound("Could not find config file at {}, please follow the instructions in the link to setup the config file https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm".format(expanded_file_location))
oci.exceptions.ConfigFileNotFound: Could not find config file at /root/.oci/config, please follow the instructions in the link to setup the config file https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm
INFO: Reading Json File : /okit/instance/templates/reference_architecture/database/postgresql_cluster.json
INFO: Reading Json File : /okit/instance/templates/reference_architecture/infrastructure/ha_web_application.json
INFO: Reading Json File : /okit/instance/templates/reference_architecture/infrastructure/hub_and_spoke_network_topology.json


```

**Comment by davidkhala** [comment]
A hints here, we are using podman as docker alias.

**Comment by davidkhala** [comment]
self-resolved. Tips for people seeing similar issue: recent podman release enhance on permission security so we need to add flag `--privileged` to command `docker run ...`, such as 

```
docker run -d --privileged -p 80:80 --volume ~/.oci:/root/.oci --volume ~/.ssh:/root/.ssh --name okit davidkhala/okit

```
