### ISSUE TITLE
Key File /Users/atael/.ssh/oci_api_key.pem does not exist

### ISSUE THREAD

**Issue by andytael** [oracle/oci-designer-toolkit#487]
When looking at the docker console I see the following messages when starting the container:

```
INFO: Config Sections ['DEFAULT', 'TALLEN67', 'OCIOBPARTNER']
INFO: ['[DEFAULT] Key File /Users/atael/.ssh/oci_api_key.pem does not exist.', '[TALLEN67] Key File /Users/atael/.ssh/oci_api_key.pem does not exist.', '[OCIOBPARTNER] Key File /Users/atael/.ssh/oci_api_key.pem does not exist.']
INFO: Config Sections ['DEFAULT', 'TALLEN67', 'OCIOBPARTNER']
INFO: Config Sections {'sections': ['DEFAULT', 'TALLEN67', 'OCIOBPARTNER']}
INFO: []
INFO: Config Settings {'gitsections': []}
INFO: Reading Json File : /okit/instance/templates/reference_architecture/infrastructure/hub_and_spoke_network_topology.json
INFO: Reading Json File : /okit/instance/templates/reference_architecture/infrastructure/ha_web_application.json
INFO: Reading Json File : /okit/instance/templates/reference_architecture/database/mysql_ha_cluster.json
INFO: []
INFO: Reading Json File : /okit/instance/templates/reference_architecture/database/postgresql_cluster.json
INFO: Reading Json File : /okit/instance/templates/reference_architecture/database/cockroachdb_cluster.json
INFO: Reading Json File : /okit/instance/templates/reference_architecture/database/sql_server.json
[2021-10-21 20:24:25 +0000] [45] [ERROR] Error handling request /okit/oci/regions/DEFAULT
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/github/oci-designer-toolkit/okitweb/okitOci.py", line 227, in ociRegions
    oci_region_query = OCIRegionQuery(profile=profile)
  File "/okit/visualiser/query/ociRegionQuery.py", line 33, in __init__
    super(OCIRegionQuery, self).__init__(config=config, configfile=configfile, profile=profile)
  File "/okit/visualiser/facades/ociConnection.py", line 41, in __init__
    self.signerFromConfig()
  File "/okit/visualiser/facades/ociConnection.py", line 64, in signerFromConfig
    self.loadConfig()
  File "/okit/visualiser/facades/ociConnection.py", line 87, in loadConfig
    self.config = oci.config.from_file(profile_name=self.profile)
  File "/usr/local/lib/python3.6/site-packages/oci/config.py", line 119, in from_file
    invalid_key_file_path_checker(config, expanded_file_location, profile_name)
  File "/usr/local/lib/python3.6/site-packages/oci/config.py", line 223, in invalid_key_file_path_checker
    raise InvalidKeyFilePath(message)
oci.exceptions.InvalidKeyFilePath: Config file /root/.oci/config is invalid: the key_file's value '/Users/atael/.ssh/oci_api_key.pem' at line 4 must be a valid file path.
```
The file exists:

```
atael@ATAEL-mac ~ % ls -ltr /Users/atael/.ssh/oci_api_key.pem
-rw-------  1 atael  staff  1679 Jul 12 13:47 /Users/atael/.ssh/oci_api_key.pem
```
I am using Docker desktop 4.1.1 on MacOS 11.6. The OKIT Version: 0.28.0 (20th October 2021)

Don't now what it affects (yet)

**Comment by andytael** [comment]
The issue is that the file /Users/atael/.ssh/oci_api_key.pem doesn't exist in the same location on the docker container. It exists in the /root/.ssh location.
