### ISSUE TITLE
unable to connect to the OCI tenancy

### ISSUE THREAD

**Issue by kollachaitanyakrishna** [oracle/oci-designer-toolkit#490]
V0.28
logged in to the oci with "oci setup config", but still unable to login

cd: /projects/okit/okit: No such file or directory
[2021-10-29 17:25:31 +0000] [155] [INFO] Starting gunicorn 20.1.0
[2021-10-29 17:25:31 +0000] [155] [INFO] Listening at: http://0.0.0.0:7070 (155)
[2021-10-29 17:25:31 +0000] [155] [INFO] Using worker: sync
[2021-10-29 17:25:31 +0000] [158] [INFO] Booting worker with pid: 158
[2021-10-29 17:25:31 +0000] [159] [INFO] Booting worker with pid: 159
[2021-10-29 17:25:31 +0000] [160] [INFO] Booting worker with pid: 160
INFO: Reading Json File : /okit/okitweb/static/okit/palette/palette.json
INFO: Config Sections ['DEFAULT']
INFO: Config Sections ['DEFAULT']
INFO: []
INFO: Config Sections {'sections': ['DEFAULT']}
INFO: []
INFO: Config Settings {'gitsections': []}
INFO: []
ERROR: [Errno 2] No such file or directory: '/okit/instance/local'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/okit/okitweb/okitWebDesigner.py", line 452, in local_panel
    local_filesystem = [dir_to_json(local_filesystem_dir, current_app.instance_path, 'children', 'templates')]
  File "/okit/okitweb/okitWebDesigner.py", line 316, in dir_to_json
    with os.scandir(rootdir) as it:
FileNotFoundError: [Errno 2] No such file or directory: '/okit/instance/local'
ERROR: [Errno 2] No such file or directory: '/okit/instance/templates/reference_architecture'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/okit/okitweb/okitWebDesigner.py", line 286, in templates_panel
    ref_arch_templates = dir_to_json(ref_arch_root, current_app.instance_path, 'children', 'templates')
  File "/okit/okitweb/okitWebDesigner.py", line 316, in dir_to_json
    with os.scandir(rootdir) as it:
FileNotFoundError: [Errno 2] No such file or directory: '/okit/instance/templates/reference_architecture'
INFO: Querying Regions
INFO: {'opc-request-id': '09BD4C1D26994164A26A13BA58DE4728/D2F0C2CF5FC4E4AAA56F0922B41A0FED/7E7414EE546438F93C95830FDC7A6B66', 'code': 'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401}
INFO: The required information to complete authentication was not provided or was incorrect.
ERROR: {'opc-request-id': '09BD4C1D26994164A26A13BA58DE4728/D2F0C2CF5FC4E4AAA56F0922B41A0FED/7E7414EE546438F93C95830FDC7A6B66', 'code': 'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/okit/okitweb/okitOci.py", line 228, in ociRegions
    regions = oci_region_query.executeQuery()
  File "/okit/visualiser/query/ociRegionQuery.py", line 40, in executeQuery
    discovery_client = OciResourceDiscoveryClient(self.config, self.signer, include_resource_types=self.SUPPORTED_RESOURCES)
  File "/okit/visualiser/discovery/oci_discovery_client.py", line 409, in __init__
    self.tenancy = self.get_tenancy()
  File "/okit/visualiser/discovery/oci_discovery_client.py", line 484, in get_tenancy
    tenancy = identity.get_tenancy(self.config["tenancy"]).data
  File "/usr/local/lib/python3.6/site-packages/oci/identity/identity_client.py", line 5358, in get_tenancy
    response_type="Tenancy")
  File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 454, in call_api
    response = self.request(request)
  File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 583, in request
    self.raise_service_error(request, response, service_code, message)
  File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 745, in raise_service_error
    original_request=request)
oci.exceptions.ServiceError: {'opc-request-id': '09BD4C1D26994164A26A13BA58DE4728/D2F0C2CF5FC4E4AAA56F0922B41A0FED/7E7414EE546438F93C95830FDC7A6B66', 'code': 'NotAuthenticated', 'message': 'The required information to complete authentication was not provided or was incorrect.', 'status': 401}

**Comment by toxophilist** [comment]
@kollachaitanyakrishna this due to a miss configuration in your config file. The usual issue is the location of the key file which will always be in /root/.oci/<FILE_NAME> and should be specified as ~/.oci/<FILE_NAME> in the config
