### ISSUE TITLE
Console log tells me that the OKIT is looking for a .pem file 

### ISSUE THREAD

**Issue by andytael** [oracle/oci-designer-toolkit#5]
The console from where I executed `./start-okit-server.sh` loks like this:
```
atael@atael-mac docker % ./start-okit-server.sh
OCI_CONFIG_DIR has not been set using /Users/atael/.oci
OKIT_OUTPUT_DIR has not been set using /Users/atael/github/oci-designer-toolkit/output



==========================================================================
=====  Runtime : gunicorn                                            =====
=====  Version : 0.5.0                                               =====
=====  Image   : okit/0.5.0/webserver                                =====
==========================================================================



[2020-05-13 20:35:58 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-05-13 20:35:58 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2020-05-13 20:35:58 +0000] [1] [INFO] Using worker: sync
[2020-05-13 20:35:58 +0000] [8] [INFO] Booting worker with pid: 8
[2020-05-13 20:35:58 +0000] [9] [INFO] Booting worker with pid: 9
INFO: Fragment : bastion_server.svg
INFO: Fragment full : /okit/okitweb/static/okit/fragments/svg/bastion_server.svg
INFO: Icon : {'svg': 'bastion_server.svg', 'title': 'Bastion Server'}
INFO: Fragment : load_balanced_nginx.svg
INFO: Fragment full : /okit/okitweb/static/okit/fragments/svg/load_balanced_nginx.svg
INFO: Icon : {'svg': 'load_balanced_nginx.svg', 'title': 'Load Balanced Nginx'}
INFO: Reading Json File : /okit/okitweb/static/okit/templates/infrastructure/bastion_server.json
INFO: Reading Json File : /okit/okitweb/static/okit/templates/network/load_balanced_nginx.json
INFO: Reading Json File : /okit/okitweb/static/okit/templates/network/simple_load_balancer.json
INFO: Reading Json File : /okit/okitweb/static/okit/templates/reference_architecture/cockroachdb_cluster.json
INFO: Reading Json File : /okit/okitweb/static/okit/json/dropdown.json
ERROR: [Errno 2] No such file or directory: '/Users/atael/.ssh/oci_api_key.pem'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/okit/okitweb/okitWebDesigner.py", line 451, in dropdownQuery
    oci_shapes = OCIShapes()
  File "/okit/visualiser/facades/ociShape.py", line 31, in __init__
    super(OCIShapes, self).__init__(config=config, configfile=configfile, profile=profile)
  File "/okit/visualiser/facades/ociConnection.py", line 95, in __init__
    super(OCIComputeConnection, self).__init__(config=config, configfile=configfile, profile=profile)
  File "/okit/visualiser/facades/ociConnection.py", line 47, in __init__
    self.connect()
  File "/okit/visualiser/facades/ociConnection.py", line 98, in connect
    self.client = oci.core.ComputeClient(self.config)
  File "/usr/local/lib/python3.6/site-packages/oci/core/compute_client.py", line 73, in __init__
    private_key_content=config.get("key_content")
  File "/usr/local/lib/python3.6/site-packages/oci/signer.py", line 226, in __init__
    self.private_key = load_private_key_from_file(private_key_file_location, pass_phrase)
  File "/usr/local/lib/python3.6/site-packages/oci/signer.py", line 27, in load_private_key_from_file
    with io.open(filename, mode="rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/atael/.ssh/oci_api_key.pem'
^C[2020-05-13 20:36:43 +0000] [1] [INFO] Handling signal: int
[2020-05-13 20:36:43 +0000] [9] [INFO] Worker exiting (pid: 9)
[2020-05-13 20:36:43 +0000] [8] [INFO] Worker exiting (pid: 8)
[2020-05-13 20:36:44 +0000] [1] [INFO] Shutting down: Master
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                     PORTS               NAMES
ddf8f1ea3120        oracle/database:18.4.0-xe   "/bin/sh -c 'exec $O…"   6 weeks ago         Exited (137) 6 weeks ago                       db1840xe
```
Not sure why it is looking for the file `/Users/atael/.ssh/oci_api_key.pem`

The file exists:
```
atael@atael-mac docker % ls /Users/atael/.ssh/oci_api_key.pem
/Users/atael/.ssh/oci_api_key.pem
```

**Comment by toxophilist** [comment]
I suspect this is because of the key_file entry in your oci config file. This entry should not contain absolute path but rather look like:

```properties
[DEFAULT]
user=ocid1.user.oc1..aaaaaaaak6z......
fingerprint=3b:7e:37:ec:a0:86:1....
key_file=~/.oci/oci_api_key.pem
tenancy=ocid1.tenancy.oc1..aaaaaaaawpqblfem........
region=us-phoenix-1

```
The reason for this is that during the start process we map the ~/.oci config directory on your machine to the docker/vagrant users ~/.oci and hence within the docker container it will not find /Users/atael/.ssh directory.

**Comment by toxophilist** [comment]
Updated documentation to make it more explicit that the key_file must not be an absolute path on the host.
