### ISSUE TITLE
Windows 10 / WSL (Ubuntu) execution error

### ISSUE THREAD

**Issue by antoniogomezr** [oracle/oci-designer-toolkit#565]
AttributeError: module 'oci.apigateway' has no attribute 'UsagePlansClient'
[2022-11-25 15:07:20 +0100] [6435] [ERROR] Exception in worker process

**Comment by antoniogomezr** [comment]
File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/antgomez/okit/okitweb/okitweb/wsgi.py", line 17, in <module>
    app = create_local_app()
  File "/home/antgomez/okit/okitweb/okitweb/__init__.py", line 66, in create_local_app
    from . import okitOci
  File "/home/antgomez/okit/okitweb/okitweb/okitOci.py", line 84, in <module>
    from query.ociQuery import OCIQuery
  File "/home/antgomez/okit/visualiser/query/ociQuery.py", line 22, in <module>
    from discovery import OciResourceDiscoveryClient
  File "/home/antgomez/okit/visualiser/discovery/__init__.py", line 3, in <module>
    from .oci_discovery_client import OciResourceDiscoveryClient
  File "/home/antgomez/okit/visualiser/discovery/oci_discovery_client.py", line 20, in <module>
    class OciResourceDiscoveryClient(object):
  File "/home/antgomez/okit/visualiser/discovery/oci_discovery_client.py", line 27, in OciResourceDiscoveryClient
    "ApiGatewayUsagePlanDetails": (oci.apigateway.UsagePlansClient, "get_usage_plan"), # used to get full details
AttributeError: module 'oci.apigateway' has no attribute 'UsagePlansClient'
[2022-11-25 12:55:09 +0100] [148] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/antgomez/okit/okitweb/okitweb/wsgi.py", line 17, in <module>
    app = create_local_app()
  File "/home/antgomez/okit/okitweb/okitweb/__init__.py", line 66, in create_local_app
    from . import okitOci
  File "/home/antgomez/okit/okitweb/okitweb/okitOci.py", line 84, in <module>
    from query.ociQuery import OCIQuery
  File "/home/antgomez/okit/visualiser/query/ociQuery.py", line 22, in <module>
    from discovery import OciResourceDiscoveryClient
  File "/home/antgomez/okit/visualiser/discovery/__init__.py", line 3, in <module>
    from .oci_discovery_client import OciResourceDiscoveryClient
  File "/home/antgomez/okit/visualiser/discovery/oci_discovery_client.py", line 20, in <module>
    class OciResourceDiscoveryClient(object):
  File "/home/antgomez/okit/visualiser/discovery/oci_discovery_client.py", line 27, in OciResourceDiscoveryClient
    "ApiGatewayUsagePlanDetails": (oci.apigateway.UsagePlansClient, "get_usage_plan"), # used to get full details
AttributeError: module 'oci.apigateway' has no attribute 'UsagePlansClient'
[2022-11-25 12:55:09 +0100] [147] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/antgomez/okit/okitweb/okitweb/wsgi.py", line 17, in <module>
    app = create_local_app()
  File "/home/antgomez/okit/okitweb/okitweb/__init__.py", line 66, in create_local_app
    from . import okitOci
  File "/home/antgomez/okit/okitweb/okitweb/okitOci.py", line 84, in <module>
    from query.ociQuery import OCIQuery
  File "/home/antgomez/okit/visualiser/query/ociQuery.py", line 22, in <module>
    from discovery import OciResourceDiscoveryClient
  File "/home/antgomez/okit/visualiser/discovery/__init__.py", line 3, in <module>
    from .oci_discovery_client import OciResourceDiscoveryClient
  File "/home/antgomez/okit/visualiser/discovery/oci_discovery_client.py", line 20, in <module>
    class OciResourceDiscoveryClient(object):
  File "/home/antgomez/okit/visualiser/discovery/oci_discovery_client.py", line 27, in OciResourceDiscoveryClient
    "ApiGatewayUsagePlanDetails": (oci.apigateway.UsagePlansClient, "get_usage_plan"), # used to get full details
AttributeError: module 'oci.apigateway' has no attribute 'UsagePlansClient'
[2022-11-25 12:55:09 +0100] [149] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/antgomez/okit/okitweb/okitweb/wsgi.py", line 17, in <module>
    app = create_local_app()
  File "/home/antgomez/okit/okitweb/okitweb/__init__.py", line 66, in create_local_app
    from . import okitOci
  File "/home/antgomez/okit/okitweb/okitweb/okitOci.py", line 84, in <module>
    from query.ociQuery import OCIQuery
  File "/home/antgomez/okit/visualiser/query/ociQuery.py", line 22, in <module>
    from discovery import OciResourceDiscoveryClient
  File "/home/antgomez/okit/visualiser/discovery/__init__.py", line 3, in <module>
    from .oci_discovery_client import OciResourceDiscoveryClient
  File "/home/antgomez/okit/visualiser/discovery/oci_discovery_client.py", line 20, in <module>
    class OciResourceDiscoveryClient(object):
  File "/home/antgomez/okit/visualiser/discovery/oci_discovery_client.py", line 27, in OciResourceDiscoveryClient
    "ApiGatewayUsagePlanDetails": (oci.apigateway.UsagePlansClient, "get_usage_plan"), # used to get full details
AttributeError: module 'oci.apigateway' has no attribute 'UsagePlansClient'
[2022-11-25 12:55:09 +0100] [150] [INFO] Worker exiting (pid: 150)
[2022-11-25 12:55:09 +0100] [148] [INFO] Worker exiting (pid: 148)
[2022-11-25 12:55:09 +0100] [147] [INFO] Worker exiting (pid: 147)
[2022-11-25 12:55:09 +0100] [149] [INFO] Worker exiting (pid: 149)
Traceback (most recent call last):
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 513, in reap_workers
    wpid, status = os.waitpid(-1, os.WNOHANG)
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/antgomez/okit/.venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 390, in stop
    self.kill_workers(sig)
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 632, in kill_workers
    self.kill_worker(pid, sig)
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/antgomez/okit/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

**Comment by toxophilist** [comment]
@antoniogomezr looks like the oci python library needs upgrading can you try 
```bash
pip install oci --upgrade
```

**Comment by toxophilist** [comment]
@antoniogomezr did the upgrade work
