### ISSUE TITLE
Query won't work

### ISSUE THREAD

**Issue by nyirimark** [oracle/oci-designer-toolkit#602]
I build container.
After start, auth is succes.
I try get QUERY OCI, but won't got compartments etc.
But in the log i see it is success.

![image](https://github.com/oracle/oci-designer-toolkit/assets/22678093/16f05a59-aaae-40ca-b23c-1560c005204b)

`
INFO: cert_bundle=None
INFO: submitted 1 list resources requests
INFO: processed 1 list resources responses
INFO: found 15 active compartments
INFO: >>>>> Queried Regions [{'is_home_region': True, 'region_key': 'FRA', 'region_name': 'eu-frankfurt-1', 'status': 'READY'}]
INFO: >>>>>>>>> Regions: [
  {
    "display_name": "EU Frankfurt",
    "id": "eu-frankfurt-1",
    "is_home_region": true,
    "key": "FRA",
    "name": "eu-frankfurt-1",
    "region_key": "FRA",
    "region_name": "eu-frankfurt-1",
    "status": "READY"
  }
]`

Later i got error in log: 

No dns record found for https://identity.retrieving.oci.oraclecloud.com

`
INFO: >>>>> Queried Regions [{'is_home_region': True, 'region_key': 'FRA', 'region_name': 'eu-frankfurt-1', 'status': 'READY'}]
INFO: >>>>>>>>> Regions: [
  {
    "display_name": "EU Frankfurt",
    "id": "eu-frankfurt-1",
    "is_home_region": true,
    "key": "FRA",
    "name": "eu-frankfurt-1",
    "region_key": "FRA",
    "region_name": "eu-frankfurt-1",
    "status": "READY"
  }
]
INFO: Using Profile : DEFAULT
INFO: OCIConnection: Passed Config <class 'dict'> {'region': 'Retrieving'}
INFO: OCIConnection: Passed Config <class 'dict'> dict_keys(['region']) {'region': 'Retrieving'}
INFO: OCI_CLI_AUTH = Undefined
INFO: Request : ['Retrieving']
INFO: Request : ['Retrieving']
INFO: Request : True
INFO: cert_bundle=None
[2023-08-28 07:01:31 +0000] [18] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/urllib3/connection.py", line 179, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/urllib3/util/connection.py", line 77, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/urllib3/connectionpool.py", line 708, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/urllib3/connectionpool.py", line 391, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/urllib3/connectionpool.py", line 1045, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/urllib3/connection.py", line 191, in _new_conn
    raise NewConnectionError(
oci._vendor.urllib3.exceptions.NewConnectionError: <oci.base_client.OCIConnection object at 0x7f7199af4700>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/requests/adapters.py", line 447, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/urllib3/connectionpool.py", line 790, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/urllib3/util/retry.py", line 597, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
oci._vendor.urllib3.exceptions.MaxRetryError: OCIConnectionPool(host='identity.retrieving.oci.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/tenancies/ocid1.tenancy.oc1..****(Caused by NewConnectionError('<oci.base_client.OCIConnection object at 0x7f7199af4700>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/oci/base_client.py", line 669, in request
    response = self.session.request(
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/requests/sessions.py", line 536, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/requests/sessions.py", line 652, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/oci/_vendor/requests/adapters.py", line 527, in send
    raise ConnectionError(e, request=request)
oci._vendor.requests.exceptions.ConnectionError: (MaxRetryError("OCIConnectionPool(host='identity.retrieving.oci.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/tenancies/ocid1.tenancy.oc1..*******(Caused by NewConnectionError('<oci.base_client.OCIConnection object at 0x7f7199af4700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"), 'Request Endpoint: GET https://identity.retrieving.oci.oraclecloud.com/20160918/tenancies/ocid1.tenancy.oc1..******See https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdk_troubleshooting.htm for help troubleshooting this error, or contact support and provide this full error message.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 193, in handle_request
    util.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 641, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/github/oci-designer-toolkit/okitweb/okitOci.py", line 299, in ociQuery
    response = query.executeQuery(regions=[regions] if regions else None, compartments=[compartments] if compartments else None, include_sub_compartments=sub_compartments)
  File "/okit/visualiser/query/ociQuery.py", line 209, in executeQuery
    discovery_client = OciResourceDiscoveryClient(self.config, signer=self.signer, cert_bundle=self.cert_bundle, regions=regions, include_resource_types=self.SUPPORTED_RESOURCES, compartments=compartments, include_sub_compartments=include_sub_compartments)
  File "/okit/visualiser/discovery/oci_discovery_client.py", line 695, in __init__
    self.tenancy = self.get_tenancy(tenancy_override)
  File "/okit/visualiser/discovery/oci_discovery_client.py", line 818, in get_tenancy
    tenancy = identity.get_tenancy(self.config["tenancy"]).data
  File "/usr/local/lib/python3.8/site-packages/oci/identity/identity_client.py", line 8192, in get_tenancy
    return retry_strategy.make_retrying_call(
  File "/usr/local/lib/python3.8/site-packages/oci/retry/retry.py", line 308, in make_retrying_call
    response = func_ref(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/site-packages/oci/base_client.py", line 531, in call_api
    response = self.request(request, allow_control_chars, operation_name, api_reference_link)
  File "/usr/local/lib/python3.8/site-packages/circuitbreaker.py", line 159, in wrapper
    return call(function, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/circuitbreaker.py", line 170, in call
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/oci/base_client.py", line 692, in request
    raise exceptions.RequestException(e)
oci.exceptions.RequestException: (MaxRetryError("OCIConnectionPool(host='identity.retrieving.oci.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/tenancies/ocid1.tenancy.oc1..****(Caused by NewConnectionError('<oci.base_client.OCIConnection object at 0x7f7199af4700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"), 'Request Endpoint: GET https://identity.retrieving.oci.oraclecloud.com/20160918/tenancies/ocid1.tenancy.oc1..****See https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdk_troubleshooting.htm for help troubleshooting this error, or contact support and provide this full error message.')` #

**Comment by nyirimark** [comment]
> @nyirimark can you try the 0.54.3 release

Thanks @toxophilist !

Look like it is working now!  - Solved

Just little issue found at launch, in right top corner is now retriving always
![image](https://github.com/oracle/oci-designer-toolkit/assets/22678093/72a926b8-8998-40b5-9df0-f51a6a939ba6)

**Comment by toxophilist** [comment]
@nyirimark try the 0.54.4 release

**Comment by nyirimark** [comment]
> @nyirimark try the 0.54.4 release

Working ;)
