### ISSUE TITLE
Instances not retrieved after installing 0.9.2

### ISSUE THREAD

**Issue by pbattagl** [oracle/oci-designer-toolkit#79]
After upgrading to 0.9.2 (from 0.8.0) I noticed the existing instances are not retrieved from my tenancy; it was working fine from 0.8.0.
Found below error message who seems to point out to code issue (might be region issue though from Zurich)

2020-08-17 14:18:02,217 [ 1012]  ERROR :       _internal[0122] : Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/okit/okitweb/okitOci.py", line 230, in ociArtifacts
    response_json = oci_instances.list(filter=query_json.get('instance_filter', None))
  File "**/okit/visualiser/facades/ociInstance.py**", line 106, in list
    image = OCIImages(config=self.config, configfile=self.configfile, profile=self.profile, compartment_id=compartment_id).get(instance['source_details']['image_id'])
**KeyError: 'image_id'**

**Comment by toxophilist** [comment]
I suspect your Instance was built with Oracle Linux 7.7. This was dropped as an image hence the issue I will be adding code to mitigate this issue.

**Comment by toxophilist** [comment]
fix added in 0.10.0
